ERC1155Timelock
derivable-labs/erc1155-maturity pull request #1
Opened 2023-05-09 04:48 UTC by anhnq82

2023-05-09 09:12 UTC, Zergity requested changes
please remove unused packages in `packages.json`

and add our timelock tests from the -core repo

2023-05-11 09:13 UTC, BerlinP requested changes
I think we should use ERC1155Timelock instead of ERC1155 to avoid unnecessary confusion

2023-05-11 09:13 UTC, BerlinP commented on contracts/token/ERC1155/ERC1155.sol
>  contract ERC1155 is Context, ERC165, IERC1155, IERC1155MetadataURI {
I think we should use ERC1155Timelock instead of ERC1155 to avoid unnecessary confusion

2023-05-11 10:09 UTC, Zergity commented on contracts/token/ERC1155/ERC1155.sol
>  contract ERC1155 is Context, ERC165, IERC1155, IERC1155MetadataURI {
yes, we just have to make a separated commit for it

2023-05-12 06:57 UTC, closed without merging